server:
  listen: 0.0.0.0:2222
  
katago:
  bins:
    - name: katago
      path: ./data/bins/run-katago.sh
  weights:
    - name: a # COLAB_WEIGHT_REPLACE_MARKER
      path: b # COLAB_WEIGHT_REPLACE_MARKER
  configs:
    - name: default_gtp
      path: ./data/configs/default_gtp.cfg
    - name: 2stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=0.38
      description: 让子棋让2子配置
    - name: 3stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=0.7
      description: 让子棋让3子配置
    - name: 4stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=1.38
      description: 让子棋让4子配置
    - name: 5stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=2
      description: 让子棋让5子配置
    - name: 6stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=2.38
      description: 让子棋让6子配置
    - name: 7+stones_handicap
      path: ./data/configs/default_gtp.cfg
      overrideConfig: maxVisits=50000,allowResignation=false,resignThreshold=-0.99,playoutDoublingAdvantage=2.65,analysisWideRootNoise=0.06
      description: 让子棋让7子及以上的配置
  defaultBinName: katago
  defaultWeightName: a # COLAB_WEIGHT_REPLACE_MARKER
  defaultConfigName: default_gtp
  customConfigDir: /content/user-data

use_nat: frp

nats: # only the name configured in "user_nat" will be used
  frp:
    type: frp
    config_file: ./config/frpc.txt
  direct: 
    type: direct
    host: 192.168.1.222 # the host or ip that you can connect this server directly
    port: 2222 # generally, it should equals to the server listen port

users:
  file: ./userlist.txt
