#!/bin/sh 
CONFIG_FILE=./config/conf.yaml
WEIGHT_NAME=$1
WEIGHT_PATH=$2

CMD1="s|- name: .* # COLAB_WEIGHT_REPLACE_MARKER|- name: $WEIGHT_NAME # COLAB_WEIGHT_REPLACE_MARKER|g"
CMD2="s|path: .* # COLAB_WEIGHT_REPLACE_MARKER|path: $WEIGHT_PATH # COLAB_WEIGHT_REPLACE_MARKER|g"
CMD3="s|defaultWeightName: .* # COLAB_WEIGHT_REPLACE_MARKER|defaultWeightName: $WEIGHT_NAME # COLAB_WEIGHT_REPLACE_MARKER|g"

sed -i -e "$CMD1" $CONFIG_FILE
sed -i -e "$CMD2" $CONFIG_FILE
sed -i -e "$CMD3" $CONFIG_FILE